---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: tug2-insurgency-docker-compose
    files:
      - ./docker-compose.yaml
      - ./envoy-config.yaml
      - ./postgres-client-cert-sds.yaml
      - ./postgres-validation-context-sds.yaml
    options:
      disableNameSuffixHash: true
