---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./fileflows/ks.yaml
  - ./issuers/ks.yaml
  - ./kyoo/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
