---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-sonarr-application-blueprint
  labels:
    k8s-sidecar.home.arpa/application: authentik
type: Opaque
stringData:
  # Unfortunately this must be a secret (rather than secretGenerator) or Flux will not substitute
  # values within it
  authentik-sonarr-application-blueprint.yaml: |
    ---
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    version: 1
    metadata:
      name: Sonarr application
      labels:
        blueprints.goauthentik.io/description: Resources for Sonarr SSO
    entries:
      # Dependencies
      - model: authentik_blueprints.metaapplyblueprint
        attrs:
          identifiers:
            name: Implicit provider authentication
          required: true
      - model: authentik_blueprints.metaapplyblueprint
        attrs:
          identifiers:
            name: Password authentication flow
          required: true
      - model: authentik_blueprints.metaapplyblueprint
        attrs:
          identifiers:
            name: Invalidation flow
          required: true
      - model: authentik_blueprints.metaapplyblueprint
        attrs:
          identifiers:
            name: Blueprint library
          required: true
      # Application
      - model: authentik_providers_proxy.proxyprovider
        id: sonarr-provider
        identifiers:
          name: Sonarr
        attrs:
          name: Sonarr
          mode: forward_single
          external_host: https://sonarr.${SECRET_PUBLIC_DOMAIN_NAME}
          intercept_header_auth: true
          authentication_flow:
            !Find [authentik_flows.flow, [slug, password-authentication-flow]]
          authorization_flow:
            !Find [authentik_flows.flow, [slug, implicit-authorization-flow]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, invalidation-flow]]
          access_token_validity: hours=4
          refresh_token_validity: days=2
          property_mappings:
            - !Find [
                authentik_providers_oauth2.scopemapping,
                [name, "authentik default OAuth Mapping: Application Entitlements"],
              ]
            - !Find [
                authentik_providers_oauth2.scopemapping,
                [name, "authentik default OAuth Mapping: OpenID 'email'"],
              ]
            - !Find [
                authentik_providers_oauth2.scopemapping,
                [name, "authentik default OAuth Mapping: OpenID 'openid'"],
              ]
            - !Find [
                authentik_providers_oauth2.scopemapping,
                [name, "authentik default OAuth Mapping: OpenID 'profile'"],
              ]
            - !Find [
                authentik_providers_oauth2.scopemapping,
                [name, "authentik default OAuth Mapping: Proxy outpost reduced"],
              ]
      - model: authentik_core.application
        id: sonarr-application
        identifiers:
          slug: sonarr
        attrs:
          name: Sonarr
          slug: sonarr
          group: Downloads access
          provider: !KeyOf sonarr-provider
          policy_engine_mode: any
          meta_launch_url: https://sonarr.${SECRET_PUBLIC_DOMAIN_NAME}
          # icon: # TODO
      # Groups
      - model: authentik_core.group
        id: sonarr-group
        identifiers:
          name: Sonarr access
        attrs:
          attributes:
            discord_role_id: "${SECRET_AUTHENTIK_SONARR_DISCORD_ROLE_ID}"
      - model: authentik_policies.policybinding
        identifiers:
          order: 0
          group: !KeyOf sonarr-group
          target: !KeyOf sonarr-application
