serviceName: ""
certificates:
  ca:
    subject: {} # This is currently only supported for the CA certificate (TODO add support for user certs)
    issuerRef:
      name: self-signed
      kind: ClusterIssuer
      group: cert-manager.io
teleportDomainName: ""
users:
  streaming-replica:
    username: streaming_replica
  # example-application:
  #   name: example-application
  #   disable-reloading: true # If true, pods mounting this cert will NOT be reloaded on cert changes
